sudo: required

language: node_js

node_js:
- '8'

services:
- docker

script:
- docker-compose build

deploy:
  provider: heroku
  api_key:
    secure: HeA2GhmyNsIUB9miHYZFdgz8wTnIAfYpVdUlxSYCYhSXVGgftMx6fz5jF07rTZBs8VRYs6yYUl+zAgWB8ejUk4K4hrxe13y/O9kDiHX54L0Th+3QO7VPCcSJ//YflDu46ZJX8HKw3aAdNVrvBlrDy+Mpe2j8/GdhGrreXZTd41SLJ2Y5Jd77zIVGbUsPhM2VOhWrLpMzifVgM8Jhjr4Jl62spz1Nv5uOfSX7UNUYOL+gFEQQzVMlazeu5r7MRwUC/gMs56KziJ8FjmTAjS7Cd8mtadwtSBWF5ni+31FHMlKF0C4pzdVGzfvKqbEW3odstilxFRE8m9ycq352Hspp4vPFNjsGDLCR5BjdHsThMIG8UCX4cTbCtYf6OCX60teqUxtYTKaoIBtBNFj7BLZYQwdA1AlHsdW+KBoopfgLrPw3cJUMrA/stlY4xMt2l2W+O6kKkXcnzdsCmGhi7Tpe5AFwD52Zii0Z6rr5/KSaAFYC576NsOq85F42s5W3M3zcqGj4QweSHOpPalZetjuJtzR+eTJju3hFXTfkYubV/XKC3DVbG+3wPdlPvWdReYr2MT3J+VZavEVd+47aDWKSclvwXQDXb3PXfCeJhfGWNxMbFceIVBido9uXzu0MZDCn9zS5dtQaRLKioPkLYIo8/11XYvaidO6da8WRFMWjnkg=
  app: insidious-canoe
  on: docker  
